# theme: jekyll-theme-cayman
# With GitHub Pages Gem
remote_theme: chrisrhymes/bulma-clean-theme
title: Igor Budasov
subtitle: The page subtitle
description: Cloud Engineering, Operations, Security and Reliability
footer_menu: footer_menu
gh_sponsor: ibudasov