# theme: jekyll-theme-cayman
# theme: owner/name --> Don't forget to remove/comment the gem-based theme option
remote_theme: "jeffreytse/jekyll-theme-yat"
title: Igor Budasov
description: Cloud Engineering, Operations, Security and Reliability
