remote_theme: pages-themes/cayman@v0.2.0
plugins:
- jekyll-remote-theme # add this line to the plugins list if you already have one
title: Igor Budasov
show_downloads: true
description: Cloud Engineering, Operations, Security and Reliability
github:
  zip_url: https://github.com/ibudasov/ibudasov/blob/main/Igor_Budasov_CV.pdf
  book_a_call: https://cal.com/igor-f9isjp/15min