# theme: jekyll-theme-cayman
# With GitHub Pages Gem
remote_theme: chrisrhymes/bulma-clean-theme
title: Igor Budasov
description: Cloud Engineering, Operations, Security and Reliability
github:
  zip_url: https://github.com/ibudasov/ibudasov/blob/main/Igor_Budasov_CV.pdf
  book_a_call: https://cal.com/igor-f9isjp/15min